from __future__ import annotations

import asyncio
import base64
from datetime import datetime, timezone
from io import BytesIO

from sqlalchemy import select
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

from app.core.config import settings
from app.models.crm.customer import Customer
from app.models.export_mgmt.export_document import ExportDocument
from app.models.export_mgmt.export_order import ExportOrder


async def _generate_export_document_async(doc_id: str) -> None:
    engine = create_async_engine(settings.database_url, pool_pre_ping=True)
    session_factory = async_sessionmaker(bind=engine, expire_on_commit=False)
    async with session_factory() as session:
        res = await session.execute(select(ExportDocument).where(ExportDocument.id == doc_id))
        doc = res.scalar_one_or_none()
        if doc is None:
            return

        order = (
            await session.execute(select(ExportOrder).where(ExportOrder.id == doc.export_order_id))
        ).scalar_one_or_none()
        customer = None
        if order is not None:
            customer = (
                await session.execute(select(Customer).where(Customer.id == order.customer_id))
            ).scalar_one_or_none()

        if order is None:
            doc.status = "failed"
            doc.content = "Order not found"
            await session.commit()
            return

        customer_name = customer.name if customer else "Unknown Customer"

        lines = [
            f"Document Type: {doc.kind}",
            f"Generated At: {datetime.now(timezone.utc).isoformat()}",
            "",
            f"Order No: {order.order_no}",
            f"Customer: {customer_name}",
            f"Destination: {order.destination_country}",
            f"Order Date: {order.order_date.isoformat()}",
            f"Status: {order.status}",
            "",
            "Generated by MnD Business Suite.",
        ]

        # PDF generation (optional dependency). If unavailable, fall back to text/plain.
        try:
            from reportlab.pdfgen import canvas  # type: ignore

            buf = BytesIO()
            c = canvas.Canvas(buf)
            y = 800
            for ln in lines:
                c.drawString(48, y, ln)
                y -= 16
            c.showPage()
            c.save()
            pdf = buf.getvalue()
            doc.content = base64.b64encode(pdf).decode("ascii")
            doc.content_type = "application/pdf"
            doc.encoding = "base64"
            doc.file_name = f"{doc.kind}-{order.order_no}.pdf"
            doc.status = "ready"
            doc.generated_at = datetime.now(timezone.utc)
        except Exception:
            doc.content = "\n".join(lines)
            doc.content_type = "text/plain"
            doc.encoding = "utf-8"
            doc.file_name = f"{doc.kind}-{order.order_no}.txt"
            doc.status = "ready"
            doc.generated_at = datetime.now(timezone.utc)
        await session.commit()
    await engine.dispose()


def generate_export_document(doc_id: str) -> None:
    asyncio.run(_generate_export_document_async(doc_id))


def send_notification(event_name: str, payload: dict) -> None:
    # Automation hook placeholder: wire email/SMS/webhooks here.
    # Kept sync for RQ compatibility.
    print(f"[automation] {event_name} payload={payload}")
